const fs=require('fs');
const p=process.argv[2];
let raw=fs.readFileSync(p,'utf8');
const m=raw.match(/^\s*\/\*[\s\S]*?\*\//);
const header=m?m[0]:'';
let body=raw.slice(header.length);
const j=JSON.parse(body);
const set=(k,d)=>{ if(j.sections[k]) j.sections[k].disabled=d; };
set('custom_liquid_zJkTbj',true);
set('custom_liquid_Cn6XXx',true);
set('main',true);
set('rich_text_pH4FWY',false);
set('image_banner_7RXWW3',false);
set('featured_product_86GxNJ',false);
set('featured_collection_BzYcBC',false);
const out=header+'\n'+JSON.stringify(j,null,2)+'\n';
fs.writeFileSync(p,out);
const st=j.order.map(k=>`  ${k}: ${j.sections[k].disabled?'OFF':'ON'}`);
console.log(st.join('\n'));