plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Montse\\Downloads\\Fam\\deploy-tienda-checkout"
publishOrigin = "default"
base = "C:\\Users\\Montse\\Downloads\\Fam\\deploy-tienda-checkout"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]